site_name: Documentação Pipelines Innoveo


theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - mermaid2:
      version: 10.0.2

nav:
  - Home: index.md
  - Contrato de Dados: contrato_de_dados.md

watch:
  - docs