site_name: Documentação Pipelines Innoveo


theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings
  - mermaid2:
      version: 10.0.2

watch:
  - docs


nav:
  - Home: index.md
  - Contrato de Dados: contrato_de_dados.md
